### ISSUE TITLE
How to run sequence data?

### ISSUE THREAD

**Issue by DennisInTw** [vsingh-group/oinr#1]
Hello, 
Thanks for your good work.
Could you please help provide more clearly how to run video?
BTW, if I extract multiple .png files from a video file, could I run this in sequence condition?

Thanks.

**Comment by sourav-roni** [comment]
Hi,

Thank you for the interest in our work. You can use a video file in mp4 or .npy format directly. Please refer to the dataset class used here https://github.com/vsingh-group/oinr/blob/main/sequence/datasets.py#L351 and others in the file.

You can extract them and use it as per your preference, but direct input of video file will work fine. 

Please feel free to reach out with any further question.

Thank you
